#!/usr/bin/env bash

# setting up EndeavourOS repo:
pacman-key --init && pacman -Syu --noconfirm && pacman -Syu --noconfirm base-devel 
pacman -S --noconfirm archlinux-keyring wget
wget https://raw.githubusercontent.com/endeavouros-team/EndeavourOS-ISO/main/airootfs/etc/pacman.conf
cp pacman.conf /etc/pacman.conf
wget https://raw.githubusercontent.com/endeavouros-team/Weekly-ISO-Rebuilds/main/mirrorlist
cp mirrorlist /etc/pacman.d/mirrorlist
wget https://raw.githubusercontent.com/endeavouros-team/PKGBUILDS/master/endeavouros-mirrorlist/endeavouros-mirrorlist
cp endeavouros-mirrorlist /etc/pacman.d/endeavouros-mirrorlist
pacman-key --recv-key 0F20FADC599D1C46EB556455AED8858E4B9813F1 --keyserver keyserver.ubuntu.com && pacman-key --lsign-key 0F20FADC599D1C46EB556455AED8858E4B9813F1
pacman-key --init
pacman -Sy --noconfirm endeavouros-keyring 
pacman -S --noconfirm endeavouros-mirrorlist
