#!/usr/bin/env bash
# setting up EndeavourOS repo:
pacman-key --init && pacman -Syu --noconfirm && pacman -Syu base-devel --noconfirm
pacman -Sy --noconfirm --needed archlinux-keyring wget
rm pacman.conf
wget https://raw.githubusercontent.com/endeavouros-team/EndeavourOS-ISO/main/pacman.conf
cp pacman.conf /etc/pacman.conf
wget https://raw.githubusercontent.com/endeavouros-team/PKGBUILDS/master/endeavouros-mirrorlist/endeavouros-mirrorlist
cp endeavouros-mirrorlist /etc/pacman.d/endeavouros-mirrorlist
cp mirrorlist /etc/pacman.d/mirrorlist
pacman-key --recv-key 0F20FADC599D1C46EB556455AED8858E4B9813F1 --keyserver keyserver.ubuntu.com && pacman-key --lsign-key 0F20FADC599D1C46EB556455AED8858E4B9813F1
pacman-key --recv-key 497AF50C92AD2384C56E1ACA003DB8B0CB23504F --keyserver keyserver.ubuntu.com && pacman-key --lsign-key 497AF50C92AD2384C56E1ACA003DB8B0CB23504F
pacman-key --init
pacman -Syy --noconfirm endeavouros-keyring 
pacman -S --noconfirm endeavouros-mirrorlist
#install archiso
pacman -Sy --noconfirm --needed pacman-contrib
paccache -rk0
pacman -Syu --noconfirm --needed archlinux-keyring archiso git squashfs-tools wget sudo base-devel curl lftp networkmanager pipewire-jack
