#!/usr/bin/env bash

cp "reset.sh.patch" "EndeavourOS-ISO/"
cd "EndeavourOS-ISO"
patch "reset.sh" < "reset.sh.patch"
./mkarchiso -v "." 2>&1 | tee "eosiso.log"
./reset.sh
ls out/ > /tmp/isoname
cp *.log out/
cd out/
isoname=$(cat /tmp/isoname)
sha512sum $isoname > $isoname.sha512sum
tar -czvf $isoname.tar.gz *.sha512sum *.iso *.log 
split -b1024M $isoname $isoname.split-
files=$(ls)
echo $files
