#!/usr/bin/env bash
cd "EndeavourOS-ISO"
echo "-----> systemsize:"
df -h
echo "<-----"
./mkarchiso -v "." 2>&1 | tee "eosiso.log"
ls out/ > /tmp/isoname
cp eosiso.log out/
echo "-----> systemsize:"
df -h
echo "<-----"
./reset.sh
echo "-----> systemsize:"
df -h
echo "<-----"
cd out/
isoname=$(cat /tmp/isoname)
sha512sum $isoname > $isoname.sha512sum
split -n 4 $isoname $isoname.split-
files=$(ls)
echo $files
