#!/usr/bin/env bash

tag=25.02.2.3

# clone ISO sources and join the path:
#git clone https://github.com/endeavouros-team/EndeavourOS-ISO.git

#load tarball of the ISO and unpack it
wget "https://github.com/endeavouros-team/EndeavourOS-ISO/archive/refs/tags/${tag}.tar.gz"
tar -xf ${tag}.tar.gz
mv EndeavourOS-ISO-${tag} EndeavourOS-ISO

# patch reset.sh to run it for space saving before tarballing later:
patch "EndeavourOS-ISO/reset.sh" < reset.sh.patch

# patch run_before_squashfs.sh
patch "EndeavourOS-ISO/run_before_squashfs.sh" < run_before_squashfs.sh.patch

# patch packages.x86_64
patch "EndeavourOS-ISO/packages.x86_64" < packages.x86_64.patch

#use updated mirrorlist
wget -qN --show-progress -P "EndeavourOS-ISO/" "https://raw.githubusercontent.com/endeavouros-team/Weekly-ISO-Rebuilds/main/mirrorlist"

# run preperations inside ISO structure
cd EndeavourOS-ISO

# Make sure build scripts are executable
chmod +x "./"{"mkarchiso","run_before_squashfs.sh"}

# Get mirrorlist for offline installs
mkdir "airootfs/etc/pacman.d"
wget -qN --show-progress -P "airootfs/etc/pacman.d/" "https://raw.githubusercontent.com/endeavouros-team/EndeavourOS-ISO/main/mirrorlist"

# Get wallpaper for installed system
wget -qN --show-progress -P "airootfs/root/" "https://raw.githubusercontent.com/endeavouros-team/Branding/master/backgrounds/endeavouros-wallpaper.png"

# create build user
#useradd -m -G wheel -s /bin/bash build
# downgrade squashfs-tools [nov 2025] latest version (4.7.3-1) segfaults on image creation
pacman -Syu --noconfirm
pacman -U --noconfirm https://archive.archlinux.org/packages/s/squashfs-tools/squashfs-tools-4.7.2-1-x86_64.pkg.tar.zst
useradd -m build
printf "build ALL=NOPASSWD: ALL\n" | tee -a /etc/sudoers
        chown -R build:build ./

# Build liveuser skel
chown -R build:build "airootfs/root/endeavouros-skel-liveuser"
cd "airootfs/root/endeavouros-skel-liveuser"
sudo -u build bash makepkg -f

