#!/usr/bin/env bash

tag=25.02.1.5

# clone ISO sources and join the path:
#git clone https://github.com/endeavouros-team/EndeavourOS-ISO.git

#load tarball of the ISO and unpack it
wget "https://github.com/endeavouros-team/EndeavourOS-ISO/archive/refs/tags/${tag}.tar.gz"
tar -xf ${tag}.tar.gz
mv EndeavourOS-ISO-${tag} EndeavourOS-ISO

# patch reset.sh to run it for space saving before tarballing later:
patch "EndeavourOS-ISO/reset.sh" < reset.sh.patch

# patch run_before_squashfs.sh
patch "EndeavourOS-ISO/run_before_squashfs.sh" < run_before_squashfs.sh.patch

# patch packages.x86_64
patch "EndeavourOS-ISO/packages.x86_64" < packages.x86_64.patch

# add packagechooser.conf.patch to ISO structure to run inside ISO build
cp packagechooser.conf.patch "EndeavourOS-ISO/airootfs/root/packagechooser.conf.patch"

#use updated mirrorlist
wget -qN --show-progress -P "EndeavourOS-ISO/" "https://raw.githubusercontent.com/endeavouros-team/Weekly-ISO-Rebuilds/main/mirrorlist"

# run preperations inside ISO structure
cd EndeavourOS-ISO

# Make sure build scripts are executable
chmod +x "./"{"mkarchiso","run_before_squashfs.sh"}

# Get mirrorlist for offline installs
mkdir "airootfs/etc/pacman.d"
wget -qN --show-progress -P "airootfs/etc/pacman.d/" "https://raw.githubusercontent.com/endeavouros-team/EndeavourOS-ISO/main/mirrorlist"

# create build user
#useradd -m -G wheel -s /bin/bash build
useradd -m build
printf "build ALL=NOPASSWD: ALL\n" | tee -a /etc/sudoers
        chown -R build:build ./

# Build liveuser skel
chown -R build:build "airootfs/root/endeavouros-skel-liveuser"
cd "airootfs/root/endeavouros-skel-liveuser"
sudo -u build bash makepkg -f
