#!/usr/bin/env bash

tag=25.02.1.5

# clone ISO sources and join the path:
#git clone https://github.com/endeavouros-team/EndeavourOS-ISO.git

#load tarball of the ISO and unpack it
wget "https://github.com/endeavouros-team/EndeavourOS-ISO/archive/refs/tags/${tag}.tar.gz"
tar -xf ${tag}.tar.gz
mv EndeavourOS-ISO-${tag} EndeavourOS-ISO

# fetch  package for testing [kpmcore]
#wget -qN --show-progress -P "EndeavourOS-ISO/airootfs/root/packages/" "https://archive.archlinux.org/packages/k/kpmcore/kpmcore-24.05.2-1-x86_64.pkg.tar.zst"

# patch run_before_squashfs.sh
#patch "EndeavourOS-ISO/run_before_squashfs.sh" < run_before_squashfs.sh.patch

# get missing live session wallpaper 
# cp livewall.png "EndeavourOS-ISO/airootfs/root/"

# fetch updated mirrorlist
wget -qN --show-progress -P "EndeavourOS-ISO/" "https://raw.githubusercontent.com/endeavouros-team/Weekly-ISO-Rebuilds/main/mirrorlist"

# run preperations inside ISO structure
cd EndeavourOS-ISO

# Get mirrorlist for offline installs
mkdir "airootfs/etc/pacman.d"
wget -qN --show-progress -P "airootfs/etc/pacman.d/" "https://raw.githubusercontent.com/endeavouros-team/Weekly-ISO-Rebuilds/main/mirrorlist"
# use it also for building ISO
cp "airootfs/etc/pacman.d/mirrorlist" "/etc/pacman.d/mirrorlist"

# Get wallpaper for installed system
#wget -qN --show-progress -P "airootfs/root/" "https://raw.githubusercontent.com/endeavouros-team/endeavouros-theming/master/backgrounds/endeavouros-wallpaper.png"

# Make sure build scripts are executable
chmod +x "./"{"mkarchiso","run_before_squashfs.sh"}

# create build user
#useradd -m -G wheel -s /bin/bash build
useradd -m build
printf "build ALL=NOPASSWD: ALL\n" | tee -a /etc/sudoers
        chown -R build:build ./

# Build liveuser skel
get_pkg() {
    pacman -Syw "$1" --noconfirm --cachedir "airootfs/root/packages"
}

get_pkg "eos-settings-plasma"

# Make sure build scripts are executable
chmod +x "./"{"mkarchiso","run_before_squashfs.sh"}

get_pkg() {
    sudo pacman -Syw "$1" --noconfirm --cachedir "airootfs/root/packages" \
    && sudo chown build:build "airootfs/root/packages/"*".pkg.tar"*
}

get_pkg "eos-settings-plasma"

# Build liveuser skel
cd "airootfs/root/endeavouros-skel-liveuser"
sudo -u build bash makepkg -f
#sudo -u build makepkg -f
